sources:
  - name: jaffle_shop
    database: jaffle_shop
    schema: raw
    tables:
      - name: customers
        description: "this is a customer table"
      - name: orders 
        discription: "this is a orders table"